version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://maryel-n_a:Admin0125!@database/maryel-n_movies?serverVersion=8.0&charset=utf8mb4
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      - database
      - mongodb

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin0125!
      MYSQL_DATABASE: maryel-n_movies
      MYSQL_USER: maryel_n_a
      MYSQL_PASSWORD: Admin0125!
    volumes:
      - db_data:/var/lib/mysql

  mongodb:
    image: mongo:7.0.14
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: maryel_n_a
      MONGO_INITDB_ROOT_PASSWORD: Admin0125!
    volumes:
      - mongo_data:/data/db

volumes:
  db_data:
  mongo_data: