version: '3.8'

services:
  php:
    image: zoo_project
    container_name: zoo
    ports:
      - 8081:80
    volumes:
      - .:/var/www/html/
    build: 
      context: .
      dockerfile: Dockerfile

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql-maryel-n.alwaysdata.net
      PMA_USER: maryel-n_ecf
      PMA_PASSWORD: Adbdd2024<3
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80


###> doctrine/doctrine-bundle ###
  mongodb:
    image: mongo:8.0.1
    container_name: mongodb
    restart: always
    ports:
      - 27018:27018
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: utilisateur
      ME_CONFIG_MONGODB_ADMINPASSWORD: motdepasse


volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
