version: '3.8'

services:
  php:
    image: zoo_project
    container_name: zoo
    ports:
      - 8081:80
    volumes:
      - .:/var/www/html/
    build: 
      context: .
      dockerfile: Dockerfile

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql-maryel-n.alwaysdata.net
      PMA_USER: maryel-n_ecf
      PMA_PASSWORD: Adbdd2024<3
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: none
    container_name: mailhog
    ports:
      - 1025:1025 #SMTP
      - 8025:8025 #Web UI

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
