version: '3.8'

services:
  php:
    image: zoo_project
    container_name: zoo
    ports:
      - 8081:80
    volumes:
      - .:/var/www/html/
    build: 
      context: .
      dockerfile: Dockerfile
    user: "www-data"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql-maryel-n.alwaysdata.net
      PMA_USER: maryel-n_ecf
      PMA_PASSWORD: Adbdd2024<3
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80

  # mongodb:
  #   image: mongo:6.0
  #   container_name: mongozoo
  #   restart: always
  #   ports:
  #     - 8090:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: arcadia
  #     MONGO_INITDB_ROOT_PASSWORD: arcadiazoo
      
