version: '3.8'

services:
  php:
    environment:
      - APP_ENV=dev
      - DEBUG=true
  phpmyadmin:
    environment:
      - PMA_VERBOSE=1

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: none
    container_name: mailhog
    ports:
      - 1025:1025 #SMTP
      - 8025:8025 #Web UI
###< symfony/mailer ###
